name: Upwork Scraper Automation

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Debug - List Files
        run: ls -lh # This will show if jobs.db exists

      - name: Debug - Check SQLite Tables
        run: sqlite3 jobs.db ".tables" || echo "⚠️ No database found"

      - name: Debug - Show Job Entries
        run: sqlite3 jobs.db "SELECT * FROM jobs LIMIT 5;" || echo "⚠️ No jobs saved"

      - name: Run Scraper in Background
        run: nohup python app.py & sleep 10
